### ISSUE TITLE
A Help 

### ISSUE THREAD

**Issue by MidnightPhantom** [RichardTry/living_trees#2]
When I place a sapling it grows into a normal tree. Could you please help me with this so that I can also grow those cool trees

**Comment by RichardTry** [comment]
Sorry for such a long delay, for some reason I thought I had already posted the answer here.
A normal tree grows because the default ABM's settings are set to a rare update for realism. And apparently this happens less often than the Minetest Game calculates a regular tree...
You can change setting by editing [these two lines](https://github.com/RichardTry/living_trees/blob/master/init.lua#L86).
`interval` is how often to call the ABM (every world living tree recalculation).
`chance` is a chance for each tree to grow on this step of recalculation.
If I remember correctly, `interval = 2` and `chance = 1` were used in demonstration video.

Also, [these lines](https://github.com/RichardTry/living_trees/blob/master/init.lua#L268) set the leaves growth speed.

Hope it will help you! :)
I'm sorry that now I have little time for this mod and for Minetest in general. But I intend to complete this mod.

**Comment by MidnightPhantom** [comment]
I guess I will try hope you complete your mod soon.
